name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macOS-13, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get version from tag
        id: lasttag
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
        shell: bash
      - name: Parse Changelog Entry
        id: changelog
        uses: coditory/changelog-parser@v1
        with:
          path: CHANGELOG
          version: ${{ steps.lasttag.outputs.version }}
      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgirepository1.0-dev gobject-introspection
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install Libraries
        run: |
          pip install -r requirements.txt
      - name: Build
        run: |
          briefcase build -r
      - name: Package on macOS
        if: runner.os == 'macOS'
        run: |
          briefcase package --adhoc-sign
      - name: Package
        if: runner.os == 'Linux' || runner.os == 'Windows'
        run: |
          briefcase package
      - name: upload binaries to release
        uses: softprops/action-gh-release@v2
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: dist/*
          body: ${{ steps.changelog.outputs.description }}
          draft: true
          tag_name: ${{ steps.lasttag.outputs.version }}
          name: "[Alpha] X4 Tweaker ${{ steps.lasttag.outputs.version }}"
